### PR TITLE
I don't need no transpilation...

### PR DESCRIPTION
**Pull request by SethDavenport**
I don't need no syntax control.

Seriously, I realized that we're transpiling a ton of code, but not actually using any language features that need it. Node 4 supports everything we're using.

Transpiling makes the toolchain twice as complex as it needs to be, so bye-bye.

All part of my sinister plan to remove gulp.

### CODE REVIEW

**Comment by SethDavenport** [comment]
A simpler toolchain will make it easier to onboard people.

This also fixes an annoying issue with `npm run dev` where the combination of watching and transpiling would make nodemon freak out for 10s before the server stabilized.

**Comment by SethDavenport** [comment]
I seem to have borken istanbul.  Looking into it.

**Comment by SethDavenport** [comment]
Got rid of gulp too now.

**Comment by rafkhan** [comment]
@SethDavenport I'll build this and do some deploys / teardowns e2e and then :shipit: after

**Comment by bennett000** [comment]
I'm super happy that `gulp` is gone.  We didn't need it at all.

My only semi-meaningful opinion WRT transpilation is: if we don't transpile the CLI version of clusternator then our CLI users _have_ to have node >= 4.  

While I do favor making it portable a hard node >= 4 engines requirement isn't a deal breaker for me either.  I can see the more simplified tool chain being a better trade off than portability.  Plus if we're into forcing node versions we'll be able to leverage a more robust ES6 with Node 6.x when it hits LTS

**Comment by SethDavenport** [comment]
Yeah at this point I'm kind of like, SRLSY node 4 already OK?

If we have a request for node 0.12 we might be able to accommodate it with some effort but it's not really a priority.

If you're still on note 0.10 you need to update.  For security reasons if nothing else.

**Comment by bennett000** [comment]
In that case let's :shipit: and unless there's objections let's tentatively plan to adopt node 6.x when it hits LTS in the fall.  Being able to leverage the [ES6 in Node 6.x](http://node.green/ "ES6 is 93% implemented in Node 6.x") would be great.

**Pull request merged**
