### PR TITLE
Master deploy fixes for #282

### PR DESCRIPTION
**Pull request by bennett000**
This PR makes changes necessary to support master updates on CircleCI (#282)

### CODE REVIEW

**Comment by SethDavenport** [comment]
Connected to #282

**Comment by rafkhan** [comment]
:shipit:

**Comment by bennett000** [comment]
Oops I didn't realized I had to write "Connected to <issue number>" I thought I could just reference the issue.

**Comment by SethDavenport** [comment]
https://github.com/waffleio/waffle.io/wiki/FAQs#prs-and-issues

**Comment by bennett000** [comment]
Ah RTFM who would have though? Thanks :+1:

**Pull request merged**
