### PR TITLE
Add missing require for https in repl 'tests'

### PR DESCRIPTION
**Pull request by mhazy**
Missing require, added so that I can run the repl "tests" in Webstorm for debugging tools

### CODE REVIEW

**Comment by SethDavenport** [comment]
@mhazy can you clarify what this is for?

**Comment by mhazy** [comment]
Missing import for `https` usage at https://github.com/mhazy/the-clusternator/blob/fix-missing-require-https/spec/repl/setup.js#L48.

**Comment by bennett000** [comment]
_Right_ this was for that weird hack we (@xorgy and I) had to do to get around DynamoDb instances having different protocol settings.  I guess we never moved it into the REPL.

@mhazy I'm guessing this was a problem when you tried to use DDB with the REPL?  I'm mostly asking b/c this went unnoticed and I seldom (never) really use the DDB from the REPL.

**Comment by mhazy** [comment]
`https` is imported for you in the REPL so it doesn't show up as undefined. It didn't show up until I wanted to use this outside of the REPL to setup some breakpoints.

**Pull request merged**
